name: DuckDB Extensions

on:
  push:
    tags:
      - "duckdb-extensions-v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        duckdb-platform:
          - linux_amd64
          - linux_arm64
          - osx_amd64
          - osx_arm64
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - name: Install Python
        run: uv python install 3.11
      - name: Build wheel
        run: |
          uv pip install hatchling wheel --system
          cd duckdb-extensions/scripts
          python build_wheel.py ${{ matrix.duckdb-platform }}
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: duckdb-extensions-${{ matrix.duckdb-platform }}
          path: duckdb-extensions/dist

  release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch' }}
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/p/rustac-duckdb-extensions
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v7
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: "duckdb-extensions-*/*"
      - name: Publish to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: duckdb-extensions-*/
